# Generated by Django 6.0.3 on 2026-06-18 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(choices=[('FOOTBALL', 'Football'), ('PADEL', 'Padel'), ('TENNIS', 'Tennis'), ('BASKETBALL', 'Basketball'), ('CRICKET', 'Cricket'), ('BADMINTON', 'Badminton'), ('VOLLEYBALL', 'Volleyball')], max_length=20)),
                ('players_needed', models.IntegerField(default=1)),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='teams.playerpost')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='ACCEPTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='teams.playerpost')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sport_type', models.CharField(choices=[('FOOTBALL', 'Football'), ('CRICKET', 'Cricket'), ('BASKETBALL', 'Basketball'), ('TENNIS', 'Tennis'), ('PADEL', 'Padel'), ('BADMINTON', 'Badminton'), ('VOLLEYBALL', 'Volleyball')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('looking_players', models.BooleanField(default=True)),
                ('max_players', models.IntegerField(default=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captained_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='PLAYER', max_length=20)),
                ('status', models.CharField(default='APPROVED', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
            ],
        ),
    ]
