# Generated by Django 6.0.3 on 2026-06-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_gameroom_roomchat_roomplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerpost',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerrequest',
            name='post',
        ),
        migrations.RemoveField(
            model_name='playerrequest',
            name='player',
        ),
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='player',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='city',
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='sport_type',
            field=models.CharField(choices=[('FOOTBALL VOLTA', 'Football volta'), ('PADEL', 'Padel'), ('Padoal', 'Padoal')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='PlayerPost',
        ),
        migrations.DeleteModel(
            name='PlayerRequest',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
