# Generated by Django 6.0.3 on 2026-06-27 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_playerpost_player_remove_playerrequest_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='city',
            field=models.CharField(default='Cairo', max_length=100),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('STARTED', 'Started'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='sport_type',
            field=models.CharField(choices=[('FOOTBALL', 'Football'), ('PADEL', 'Padel'), ('BASKETBALL', 'Basketball'), ('TENNIS', 'Tennis')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='time',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roomplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roomplayer',
            name='status',
            field=models.CharField(choices=[('JOINED', 'Joined'), ('LEFT', 'Left')], default='JOINED', max_length=10),
        ),
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='teams.gameroom')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='RoomChat',
        ),
    ]
