# Generated by Django 6.0.3 on 2026-07-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_gameroom_city_roomchat_delete_roommessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='sport_type',
            field=models.CharField(choices=[('FOOTBALL', 'Football'), ('PADEL', 'Padel'), ('PADOAL', 'Padoal')], max_length=20),
        ),
    ]
