# Generated by Django 6.0.3 on 2026-07-01 19:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('sport_type', models.CharField(choices=[('FOOTBALL', 'Football'), ('CRICKET', 'Cricket'), ('BASKETBALL', 'Basketball'), ('TENNIS', 'Tennis'), ('PADEL', 'Padel'), ('BADMINTON', 'Badminton'), ('VOLLEYBALL', 'Volleyball'), ('MULTI', 'Multi-Sport')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='venue_logos/')),
                ('brand_color', models.CharField(default='#0066FF', max_length=7)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sport_type', models.CharField(choices=[('FOOTBALL', 'Football'), ('CRICKET', 'Cricket'), ('BASKETBALL', 'Basketball'), ('TENNIS', 'Tennis'), ('PADEL', 'Padel'), ('BADMINTON', 'Badminton'), ('VOLLEYBALL', 'Volleyball'), ('MULTI', 'Multi-Sport')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='field_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='VenueSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('slot_type', models.CharField(choices=[('BLOCKED', 'Blocked by Owner'), ('BOOKED', 'Booked by Player')], default='BLOCKED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='venues.field')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('payment_status', models.CharField(default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venues.field')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venues.venueslot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['venue', 'is_active'], name='venues_fiel_venue_i_6c2d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['sport_type'], name='venues_fiel_sport_t_3cd8a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='venueslot',
            unique_together={('field', 'date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'status'], name='venues_book_booking_59f101_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['player', '-created_at'], name='venues_book_player__d4846f_idx'),
        ),
    ]
