# Generated by Django 6.0.3 on 2026-06-17 20:32

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venueslot',
            name='slot_type',
            field=models.CharField(choices=[('BLOCKED', 'Blocked by Owner'), ('BOOKED', 'Booked by Player')], default='BLOCKED', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='field',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'status'], name='venues_book_booking_59f101_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['player', '-created_at'], name='venues_book_player__d4846f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['field', 'booking_date'], name='venues_book_field_i_0b0214_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['venue', 'is_active'], name='venues_fiel_venue_i_6c2d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['sport_type'], name='venues_fiel_sport_t_3cd8a8_idx'),
        ),
        migrations.AddIndex(
            model_name='venueslot',
            index=models.Index(fields=['field', 'date', 'is_available'], name='venues_venu_field_i_0b9df2_idx'),
        ),
        migrations.AddIndex(
            model_name='venueslot',
            index=models.Index(fields=['date', 'is_available'], name='venues_venu_date_295b02_idx'),
        ),
    ]
