# Generated by Django 6.0.3 on 2026-06-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_alter_booking_options_booking_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='field_images/'),
        ),
        migrations.AlterField(
            model_name='field',
            name='sport_type',
            field=models.CharField(choices=[('FOOTBALL', 'Football'), ('CRICKET', 'Cricket'), ('BASKETBALL', 'Basketball'), ('TENNIS', 'Tennis'), ('PADEL', 'Padel'), ('BADMINTON', 'Badminton'), ('VOLLEYBALL', 'Volleyball'), ('MULTI', 'Multi-Sport')], max_length=20),
        ),
        migrations.AlterField(
            model_name='venue',
            name='sport_type',
            field=models.CharField(choices=[('FOOTBALL', 'Football'), ('CRICKET', 'Cricket'), ('BASKETBALL', 'Basketball'), ('TENNIS', 'Tennis'), ('PADEL', 'Padel'), ('BADMINTON', 'Badminton'), ('VOLLEYBALL', 'Volleyball'), ('MULTI', 'Multi-Sport')], max_length=20),
        ),
    ]
