# Generated by Django 6.0.3 on 2026-06-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_field_image_alter_field_sport_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='venues_book_field_i_0b0214_idx',
        ),
        migrations.RemoveIndex(
            model_name='venueslot',
            name='venues_venu_date_295b02_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='venue',
            name='brand_color',
            field=models.CharField(default='#0066FF', max_length=7),
        ),
        migrations.AddField(
            model_name='venue',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='venue',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='venue_logos/'),
        ),
    ]
