# Generated by Django 6.0.3 on 2026-06-21 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_remove_booking_venues_book_field_i_0b0214_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venueslot',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='venueslot',
            name='venues_venu_field_i_0b9df2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='venueslot',
            unique_together={('field', 'date', 'start_time')},
        ),
    ]
