# Generated by Django 6.0.3 on 2026-07-02 19:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_alter_venueslot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venueslot',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='venueslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='venues.venueslot'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='venueslot',
            name='slot_type',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BLOCKED', 'Blocked by Owner'), ('BOOKED', 'Booked by Player')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='venueslot',
            index=models.Index(fields=['field', 'date', 'is_available'], name='venues_venu_field_i_0b9df2_idx'),
        ),
        migrations.AddConstraint(
            model_name='venueslot',
            constraint=models.UniqueConstraint(fields=('field', 'date', 'start_time'), name='unique_field_slot'),
        ),
    ]
