# Generated by Django 6.0.3 on 2026-07-03 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_alter_venueslot_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='slots',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='venues.venueslot'),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('LOCKED', 'Locked - Awaiting Payment'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='venueslot',
            name='slot_type',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('LOCKED', 'Locked - Pending Payment'), ('BLOCKED', 'Blocked by Owner'), ('BOOKED', 'Booked by Player')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['locked_until'], name='venues_book_locked__664046_idx'),
        ),
    ]
