# Generated by Django 6.0.3 on 2026-07-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_remove_booking_slot_booking_locked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
