# Generated by Django 6.0.3 on 2026-07-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_remove_venue_guest_email_remove_venue_guest_name_and_more'),
    ]

    operations = [
    ]
