# Generated by Django 6.0.3 on 2026-07-12 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0010_auto_20260712_0302'),
    ]

    operations = [
    ]
