# Generated by Django 6.0.3 on 2026-07-01 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaPayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sender_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('note_code', models.CharField(blank=True, max_length=10, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='payments/screenshots/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تم التأكيد'), ('rejected', 'مرفوض'), ('manual_review', 'مراجعة يدوية'), ('expired', 'منتهي')], db_index=True, default='pending', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instapay_payment', to='booking.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_instapaypayment',
                'ordering': ['-created_at'],
            },
        ),
    ]
