# Generated by Django 6.0.3 on 2026-07-08 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('venues', '0007_remove_booking_slot_booking_locked_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instapaypayment',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='instapaypayment',
            name='screenshot_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instapaypayment',
            name='screenshot_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='instapaypayment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='venues.booking'),
        ),
    ]
