# Generated by Django 6.0.3 on 2026-07-12 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_instapaypayment_user'),
    ]

    operations = [
    ]
