# Generated by Django 6.0.3 on 2026-07-01 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('AWAITING_PAYMENT', 'في انتظار الدفع'), ('PAYMENT_REVIEW', 'مراجعة الدفع'), ('CONFIRMED', 'مؤكد'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغي'), ('EXPIRED', 'منتهي')], db_index=True, default='AWAITING_PAYMENT', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('PAID', 'مدفوع'), ('CANCELLED', 'ملغي'), ('REJECTED', 'مرفوض'), ('EXPIRED', 'منتهي')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_bookings', to='venues.field')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_booking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_slots', to='booking.booking')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings', to='venues.venueslot')),
            ],
            options={
                'db_table': 'booking_booking_slot',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'status'], name='booking_boo_booking_b98d74_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['player', '-created_at'], name='booking_boo_player__77252d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'expires_at'], name='booking_boo_status_9e1025_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingslot',
            index=models.Index(fields=['booking', 'slot'], name='booking_boo_booking_0e05b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingslot',
            unique_together={('booking', 'slot')},
        ),
    ]
